name: Main Branch Deployment

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [closed]  # 풀 리퀘스트가 닫힐 때 이벤트를 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged))
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/***/backend/pda4-team7-back
          git config --global --add safe.directory /home/***/backend/pda4-team7-back
          git pull
          echo ${{ secrets.PROD_ENV_FILE }} | sudo tee .env
          sudo npm ci
          sudo npm install --production
          sudo pm2 stop app || true
          sudo pm2 delete app || true
          sudo pm2 start app.js --name "app"

